### ISSUE TITLE
can't load searching 

### ISSUE THREAD

**Issue by KyleUltimate** [RPMTW/RPMTranslator#1]
![image](https://user-images.githubusercontent.com/68589851/130312700-77dc3432-6f9a-4442-ad58-60e429c638a8.png)

**Comment by SiongSng** [comment]
你有登入帳號了嗎?

**Comment by KyleUltimate** [comment]
yes

**Comment by KyleUltimate** [comment]
![image](https://user-images.githubusercontent.com/68589851/130317150-d1a20451-68f9-4163-8a0b-b93bb51fd0ba.png)

**Comment by SiongSng** [comment]
登出再登入測試看看

**Comment by KyleUltimate** [comment]
以嘗試，還是無法搜尋
